name: dev-build

on:
  push:
    branches: ["dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory
        run: cd $GITHUB_WORKSPACE

      - name: Java version
        run: java --version

      - name: Download flyway
        run: curl -fO https://download.red-gate.com/checkforupdates/FlywayDesktopLinuxX64.tar.gz

      - name: Extract flyway
        run: unzip FlywayDesktopLinuxX64_6.8.0.0.tar.tar.gz

      # - name: Run a multi-line script
      #   run: |
      #     mkdir root_flyway
      #     cd ./root_flyway
      #     curl -fO https://download.red-gate.com/checkforupdates/FlywayDesktopLinuxX64.tar.gz
      #     unzip FlywayDesktopLinuxX64_6.8.0.0.tar.tar.gz
      #     ls
      #     export PATH=$PATH:/home/runner/work/Flyway_CICD_Task/Flyway_CICD_Task/root_flyway
                    
      #     pwd
      #     ls

      #     toolkit provision apply
